#!/usr/bin/env python

import sys
for line in file("/usr/share/bashful/definitions"):
  if all(w in line for w in sys.argv[1:]):
    description, command = line.split(':',1)
    print description+":"
    print "\t", command

